image: ghcr.io/cpp-review-dune/introductory-review/texlive

tasks:
  - name: Say welcome
    command: |
      echo "Bienvenido(a) $USER!"
      echo 'unset JAVA_TOOL_OPTIONS' >>~/.bashrc
      echo 'alias update="yay -Syyu --noconfirm"' >>~/.bashrc
      source ~/.bashrc

github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to true)
    addComment: true
    # add a "Review in Gitpod" button to pull requests (defaults to false)
    addBadge: false
    # add a label once the prebuild is ready to pull requests (defaults to false)
    addLabel: prebuilt-in-gitpod

vscode:
  extensions:
    - ms-python.python
    - anwar.papyrus-pdf
    - twxs.cmake
    - ms-vscode.cmake-tools
    - cschlosser.doxdocgen
    - xaver.clang-format
    - TabNine.tabnine-vscode
    # - ms-vscode.cpptools@0.26.2:Pq/tmf2WN3SanVzB4xZc1g==
    # - bungcip.better-toml
    # - EditorConfig.EditorConfig
    # - kevinkyang.auto-comment-blocks
    # - ms-azuretools.vscode-docker
    # - wmaurer.change-case
    # - skellock.just
    # - wholroyd.hcl
    # - gruntfuggly.todo-tree
