name: Publish Docker image based on DuMux module v3.8.0 (dune v2.9.1)

on:
  # release:
  #   types: [published]
  push:
    branches: [main]
    paths:
      - src/Docker/DuMux.Dockerfile
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 2 1 * *"

jobs:
  push_image:
    runs-on: ubuntu-24.04

    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 34000
          remove-dotnet: "true"
          remove-android: "true"
          remove-haskell: "true"
          remove-codeql: "true"

      - name: Partial Clone
        shell: bash
        run: |
          REPO="https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git"
          git config --global user.email github-actions@github.com
          git config --global user.name github-actions
          git clone -q --filter=blob:none --no-checkout --depth=1 --sparse $REPO && cd introductory-review
          git sparse-checkout set src/Docker
          git checkout

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-dumux-cache
          key: ${{ runner.os }}-buildx-dumux-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-dumux-

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GH_USERNAME }}
          password: ${{ secrets.CR_PAT }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./introductory-review/src/Docker/DuMux.Dockerfile
          platforms: linux/amd64
          push: true
          tags: ghcr.io/cpp-review-dune/introductory-review/dumux:latest
          cache-from: type=local,src=/tmp/.buildx-dumux-cache
          cache-to: type=local,mode=max,dest=/tmp/.buildx-main-cache

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-dumux-cache
          mv /tmp/.buildx-main-cache /tmp/.buildx-dumux-cache

      # - name: Scan for vulnerabilities
      #   uses: crazy-max/ghaction-container-scan@master
      #   with:
      #     image: ghcr.io/cpp-review-dune/introductory-review/dumux:latest
      #     annotations: true
      #     severity_threshold: CRITICAL
      #     dockerfile: ./src/Docker/DuMux.Dockerfile

      - name: Prune untagged images
        uses: carlosal1015/ghcr-delete-image-action@main
        with:
          owner: cpp-review-dune
          name: introductory-review/dumux
          token: ${{ secrets.PAT }}
          untagged-keep-latest: 2