name: Deploy pages

on:
  push:
    branches: [main]
    paths:
      - docs/**
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 15 * * 5"

jobs:
  deploy_pages:
    runs-on: ubuntu-24.04

    steps:
      - name: Partial Clone
        shell: bash
        run: |
          REPO="https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git"
          git config --global user.email github-actions@github.com
          git config --global user.name github-actions
          git clone -q --filter=blob:none --no-checkout --depth=1  --sparse $REPO .
          git sparse-checkout set docs
          git checkout

      - uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install dependencies
        run: cd docs && npm install && npm run build

      - name: Download artifact
        uses: dawidd6/action-download-artifact@v5
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: latex.yml
          name: PDF-artifact

      - name: "Untar files"
        run: |
          tar -I zstd -xvf PDF.tar.zst
          mv src/TeX/*.pdf docs/public/files

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/public
